[project]
name = "be_v0.0.3"
version = "0.0.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.124.4",
    "python-multipart>=0.0.20",
    "uvicorn>=0.38.0",
    "PyJWT>=2.8.0",
]
